# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0003_auto_20170509_1647'),
        ('spatial', '0003_custom_location_types'),
    ]

    operations = [
    ]
