# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 05:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import functools
import tasks.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('type', models.CharField(choices=[('celery.accumulate', 'celery.accumulate'), ('celery.backend_cleanup', 'celery.backend_cleanup'), ('celery.chain', 'celery.chain'), ('celery.chord', 'celery.chord'), ('celery.chord_unlock', 'celery.chord_unlock'), ('celery.chunks', 'celery.chunks'), ('celery.group', 'celery.group'), ('celery.map', 'celery.map'), ('celery.starmap', 'celery.starmap')], max_length=128, verbose_name='Task function')),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('input', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=tasks.utils.fields.input_field_default, validators=[functools.partial(tasks.utils.fields.validate_type, *(dict,), **{}), tasks.utils.fields.validate_input_field])),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, validators=[functools.partial(tasks.utils.fields.validate_type, *(dict,), **{})], verbose_name='Task scheduling options')),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('log', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('immutable', models.NullBooleanField(verbose_name='If arguments are immutable (only applies to chained tasks).')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.BackgroundTask')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendents', to='tasks.BackgroundTask')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
